get_pci_drivers && get_usb_drivers

diff --git a/solver b/solver
--- a/solver
+++ b/solver
@@ -15,7 +15,6 @@ LANG=en_US.UTF-8
 ### Solvers
 #
 
-
 touchpad_force_reload () 
 {
 	drivers_str=$(lsmod | awk '{print $1 " "}' |  egrep '.*touch.*|.*mouse.*')
@@ -87,54 +86,6 @@ touchpad () {
 	[[ $? -eq 0 ]] && push "ACPI fue deshabilitado: $(grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub)"
 }
 
-
-rf () {
-	# bluetooth|wlan
-	type=$1
-
-	[[ $type == "wlan" ]] && pattern='phy'
-	[[ $type == "bluetooth" ]] && pattern='hci'
-
-	declare -a soft_lock
-	declare -a hard_lock
-
-	IFS=$'\n'; 
-	set -- $(rfkill list); 
-
-	argv=($@)
-	for ((i=0;i<$#;i++)); do
-		if [[ "${argv[i]}" =~ "$pattern" ]]; then 
-			device=$(echo "${argv[i]}" | egrep -o "$pattern[0-9]*")
-			id=$(echo "${argv[i]}" | egrep -o '^[0-9]*')
-			has_soft_lock=$(echo "${argv[i+1]}" | grep -o 'yes')
-			has_hard_lock=$(echo "${argv[i+2]}" | grep -o 'yes')
-
-			[[ ! -z $has_soft_lock ]] && soft_lock=("${soft_lock[@]}" "$id")	
-			[[ ! -z $has_hard_lock ]] && hard_lock=("${hard_lock[@]}" "$id")
-
-			if [[ ! -z $has_soft_lock  ]]; then
-				if [[ -z $has_hard_lock ]]; then
-					push "Un dispositivo $type (id=$id) bloqueado por soft, desbloqueando (..)"
-					rfkill unblock $id 2>/dev/null	
-					sleep 1	
-					if [[ ! -z $(rfkill list | grep -A 2 "$device" | grep -i 'Soft blocked: no') ]]; then 
-						push "Dispositivo $type desbloqueado -OK"
-					else
-						push "Dispositivo $type no pudo ser desbloqueado"
-					fi	
-				else
-					push "Un dispositivo $type (id=$id) bloqueado por hard"
-				fi	
-			fi
-		fi
-		i=$i+2
-	done	
-
-	[[ "${soft_lock[@]}" -eq 0 ]] && [[ "${hard_lock[@]}" -eq 0 ]] && push "No hay dispositivos $type bloqueados" "v"
-
-}
-
-
 # -- OK
 bluetooth () {
 	# bloqueado ? desbloquear 
@@ -143,22 +94,14 @@ bluetooth () {
 
 # --OK
 sound () {
-	local hardware=$(lspci -v | grep -i -A7 audio  | grep -i 'Subsystem' | cut -d':' -f2 | cut -c2- )
-	local driver_en_uso=$(lspci -v | grep -i -A7 audio  | grep 'Kernel driver in use' | cut -d':' -f2  | cut -c2-)
-	local drivers=$(lspci -v | grep -i -A7 audio  | grep 'Kernel modules' | cut -d':' -f2  | cut -c2-)
+	get_pci_driver 'audio'
 
-	# No hay driver en uso?
-	if [[ -z "$driver_en_uso" ]]; then
-		push "Audio: no hay driver activo (drivers disponibles: $drivers, device: $hardware)"
+	set -f; IFS=',' 
+	set -- $drivers
+	set +f; unset IFS
+	driver_list=($@)
 
-		# Verifico que ningún driver esté blacklisted
-		for driver in "${drivers[@]}"; do
-			in_array "$driver" "${blacklist[@]}"
-			[[ $? -eq 0 ]] && push "Audio: $driver está en blacklist"
-		done	
-	else
-		push "Driver '$driver_en_uso' para '$hardware' -OK" "v"
-	fi
+	blacklist_check
 
 	# muted?
 	muted=$(pacmd list-sinks | awk '/muted/ { print $2 }')
@@ -220,23 +163,14 @@ performance () {
 # Detectar errores de Ethernet
 ethernet () 
 {
-	local hardware=$(lspci -k | grep -i -A2 Ethernet | grep -i 'Subsystem' | cut -d':' -f2 | cut -c2-)
-	local driver_en_uso=$(lspci -k | grep -i -A3 Ethernet | grep 'in use:' | cut -d: -f2 | cut -c2-)
-	local drivers=$(lspci -k | grep -i -A2 Ethernet | grep -i 'Kernel modules:' | cut -d: -f2 | cut -c2-)
+	get_pci_driver 'ethernet'
 
-	# No hay driver en uso?
-	if [[ -z "$driver_en_uso" ]]; then
-		push "Ethernet: no hay driver activo (drivers disponibles: $drivers, device: $hardware)"
+	set -f; IFS=',' 
+	set -- $drivers
+	set +f; unset IFS
+	driver_list=($@)
 
-		# Verifico que ningún driver esté blacklisted
-		for driver in "${drivers[@]}"; do
-			in_array "$driver" "${blacklist[@]}"
-			[[ $? -eq 0 ]] && push "Ethernet: $driver está en blacklist"
-		done
-	else 
-		push "Driver '$driver_en_uso' en uso para '$hardware' -OK" "v"	
-	fi
-
+	blacklist_check
 
 	interfaces=$(ls /sys/class/net | grep '^e.*')
 
@@ -299,35 +233,20 @@ ethernet ()
 }
 
 # Detectar errores de wifi
-wireless () {
-
+wireless () 
+{
 	# PCI
-	local hardware=$(lspci -k | grep -i -A2 wireless | grep -i 'Subsystem' | cut -d':' -f2 | cut -c2-)
-	local driver_en_uso=$(lspci -k | grep -i -A3 wireless | grep 'in use:' | cut -d: -f2 | cut -c2-)
-	local drivers=$(lspci -k | grep -i -A2 wireless | grep -i 'Kernel modules:' | cut -d: -f2 | cut -c2-)
+	get_pci_driver 'wireless'
 
-	# No hay driver en uso?
-	if [[ -z "$driver_en_uso" ]]; then
-		push "Wireless: no hay driver activo (drivers disponibles: $drivers, device: $hardware)"
+	set -f; IFS=',' 
+	set -- $drivers
+	set +f; unset IFS
+	driver_list=($@)
 
-		# Verifico que ningún driver esté blacklisted
-		blacklisted=0
-		for driver in "${drivers[@]}"; do
-			in_array "$driver" "${blacklist[@]}"
-			[[ $? -eq 0 ]] && { blacklisted=1; push "Wireless: $driver está en blacklist"; }
-		done	
-		[[ $blacklisted -eq 0 ]] && push "No hay drivers en blacklist -OK" "v"
-	else 
-		push "Driver '$driver_en_uso' en uso para '$hardware' -OK" "v"		
-	fi
+	blacklist_check
 
 	# USB
-	local raw=$((sudo lsusb -v 2>/dev/null) | grep -B22 -i "Wireless Network Card")
-	local id_vendor=$(echo "$raw" | grep idVendor | awk '{print $2}' | cut -dx -f2)
-	local id_product=$(echo "$raw" | grep idProduct | awk '{print $2}' | cut -dx -f2)
-
-	hardware=$(echo "$raw" | grep iProduct | awk '{print $3}')
-	driver_en_uso=$(usb-devices | grep -A5 "Vendor=$id_vendor ProdID=$id_product" | grep -o Driver=[a-z0-9\-]* | cut -d= -f2)
+	get_usb_driver "Wireless Network Card"
 
 	# No hay driver en uso?
 	if [[ ! -z "$hardware" ]]; then
@@ -412,9 +331,225 @@ wireless () {
 	done
 }
 
+
+video () 
+{
+	push 'No implementado (aún)'
+	return
+
+	######################
+
+	get_pci_driver 'vga|3d|2d|display'
+
+	set -f; IFS=',' 
+	set -- $drivers
+	set +f; unset IFS
+	driver_list=($@)
+
+	blacklist_check
+}
+
 #
 ## Utils
 #
+
+get_pci_driver ()
+{
+	local search="$1"
+
+	local addr=$(lspci | egrep -i "$search" | grep -o '[0-9][0-9]:[0-9a-f][0-9a-f].[0-9a-f]')
+	[[ -z $addr ]] && return
+	local reg=$(lspci -vs "$addr")
+
+	hardware=$(echo "$reg" | grep -i 'Subsystem' | cut -d':' -f2 | cut -c2-)
+	drivers=$(echo "$reg"  | grep -i 'Kernel modules:' | cut -d: -f2 | cut -c2-)
+	driver_en_uso=$(echo "$reg" | grep 'in use:' | cut -d: -f2 | cut -c2-)
+}
+
+get_usb_driver ()
+{
+	local search="$1"
+
+	local raw=$((sudo lsusb -v 2>/dev/null) | egrep -B22 -i "$search")      # revisar  !!!!!!!
+	local id_vendor=$(echo "$raw" | grep idVendor | awk '{print $2}' | cut -dx -f2)
+	local id_product=$(echo "$raw" | grep idProduct | awk '{print $2}' | cut -dx -f2)
+
+	hardware=$(echo "$raw" | grep iProduct | awk '{print $3}')
+	driver_en_uso=$(usb-devices | grep -A5 "Vendor=$id_vendor ProdID=$id_product" | grep -o Driver=[a-z0-9\-]* | cut -d= -f2)
+}
+
+rf () {
+	# bluetooth|wlan
+	type=$1
+
+	[[ $type == "wlan" ]] && pattern='phy'
+	[[ $type == "bluetooth" ]] && pattern='hci'
+
+	declare -a soft_lock
+	declare -a hard_lock
+
+	IFS=$'\n'; 
+	set -- $(rfkill list); 
+
+	argv=($@)
+	for ((i=0;i<$#;i++)); do
+		if [[ "${argv[i]}" =~ "$pattern" ]]; then 
+			device=$(echo "${argv[i]}" | egrep -o "$pattern[0-9]*")
+			id=$(echo "${argv[i]}" | egrep -o '^[0-9]*')
+			has_soft_lock=$(echo "${argv[i+1]}" | grep -o 'yes')
+			has_hard_lock=$(echo "${argv[i+2]}" | grep -o 'yes')
+
+			[[ ! -z $has_soft_lock ]] && soft_lock=("${soft_lock[@]}" "$id")	
+			[[ ! -z $has_hard_lock ]] && hard_lock=("${hard_lock[@]}" "$id")
+
+			if [[ ! -z $has_soft_lock  ]]; then
+				if [[ -z $has_hard_lock ]]; then
+					push "Un dispositivo $type (id=$id) bloqueado por soft, desbloqueando (..)"
+					rfkill unblock $id 2>/dev/null	
+					sleep 1	
+					if [[ ! -z $(rfkill list | grep -A 2 "$device" | grep -i 'Soft blocked: no') ]]; then 
+						push "Dispositivo $type desbloqueado -OK"
+					else
+						push "Dispositivo $type no pudo ser desbloqueado"
+					fi	
+				else
+					push "Un dispositivo $type (id=$id) bloqueado por hard"
+				fi	
+			fi
+		fi
+		i=$i+2
+	done	
+
+	[[ "${soft_lock[@]}" -eq 0 ]] && [[ "${hard_lock[@]}" -eq 0 ]] && push "No hay dispositivos $type bloqueados" "v"
+
+}
+
+push () {
+	if [[ "$2" != "v" ]] || [[ "$2" == "v" && $verbose -eq 1 ]]; then
+		report=("${report[@]}" "$1")
+		echo "$1"
+	fi
+}
+
+in_array () {
+  local x
+
+  entry=$1
+  shift 1
+  array=( "$@" )
+  [ -z "${array}" ] && return 1
+  [ -z "${entry}" ] && return 1
+  
+  for x in ${array[@]}; do
+    [ "${x}" == "${entry}" ] && return 0
+  done
+  
+  return 1
+}
+
+# Sistema de paquetes utilizado, distribución, etc
+describe () {	
+	if [[ ! -z $(which apt 2>/dev/null) ]]; then
+		pkgm='apt'
+		else 
+			if [[ ! -z $(which dnf 2>/dev/null) ]]; then
+				pkgm='dnf'	
+			else
+				if [[ ! -z $(which pacman 2>/dev/null) ]]; then
+					pkgm='pacman'
+				else
+					if [[ ! -z $(which emerge 2>/dev/null) ]]; then
+						pkgm='emerge'	
+					fi	
+				fi	
+			fi	
+	fi 	
+
+	distro=`((cat /etc/*-release 2>/dev/null)| egrep '^ID=' | cut -c4-)`
+}
+
+# Drivers en lista negra
+blacklist () {
+	blacklist=$(cat /etc/modprobe.d/*blacklist* 2>/dev/null | egrep '^blacklist ' | cut -d' ' -f2)
+}
+
+blacklist_check ()
+{
+	if [[ -z $drivers ]]; then
+		push "No hay drivers para $hardware"
+	else
+		push "Drivers '${drivers[@]}' para '$hardware'" "v"
+	fi 
+
+	# No hay driver en uso?
+	if [[ -z "$driver_en_uso" ]]; then
+		push "No hay driver activo"
+
+		# Verifico que ningún driver esté blacklisted
+		for driver in "${driver_list[@]}"; do
+			in_array "$driver" "${blacklist[@]}"
+			[[ $? -eq 0 ]] && { blacklisted=1; push "Driver $driver está en blacklist"; }
+		done	
+		[[ $blacklisted -eq 0 ]] && push "No hay drivers en blacklist -OK" "v"
+	else 
+		push "Driver '$driver_en_uso' en uso para '$hardware' -OK" "v"		
+	fi
+}
+
+
+key () {
+	echo -e "\nPresione Enter para continuar..."
+	read tecla
+}
+
+# MENU
+menu () {
+	while :
+	do
+		clear
+		echo " Escoja una opción "
+		echo "==================="
+		echo "1. Verificar problemas de rendimiento"
+		echo "2. Verificar video"
+		echo "3. Verificar touchpad"
+		echo "4. Problemas con ethernet"
+		echo "5. Problemas con WiFi"
+		echo "6. Problemas con bluetooth"
+		echo "7. Problemas de sonido"
+		echo "8. Salir del programa"
+		echo -en "\nSeleccione una opción [1 - 8] "
+		read opcion
+		echo
+			case $opcion in
+			1) 	performance
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			2) 	video
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;	
+			3) 	touchpad
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			4) 	sudo true; ethernet
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			5) 	sudo true; wireless
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			6)	bluetooth
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			7)	sound
+				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+				key;;
+			8) 	exit 0
+				key;;
+			*) 	echo "'$opcion' es una opción invalida."
+				key;;
+			esac
+		unset report[@] # Reinicia variable
+	done
+}
 
 options () 
 {
@@ -432,6 +567,7 @@ options ()
 	 -i, --interactive              interactive mode (menu)
 	 -a, --all                      run all tests  
 	 -b, --bluetooth                bluetooth checking
+	 -d, --display                  video cards
 	 -t, --touchpad                 touchpad checking
 	 -w, --wireless                 wifi tests
 	 -e, --ethernet                 ethernet tests
@@ -511,7 +647,11 @@ TEXT
 	-p|--performance)
 		performance
 		[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-		;;			
+		;;	
+	-d|--display)
+		video 
+		[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
+		;;	
 	-s|--sound)
 		sound
 		[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
@@ -545,106 +685,6 @@ TEXT
 		;;
 	esac
 }
-
-key () {
-	echo -e "\nPresione Enter para continuar..."
-	read tecla
-}
-
-# MENU
-menu () {
-	while :
-	do
-		clear
-		echo " Escoja una opción "
-		echo "==================="
-		echo "1. Verificar problemas de rendimiento"
-		echo "2. Verificar touchpad"
-		echo "3. Problemas con ethernet"
-		echo "4. Problemas con WiFi"
-		echo "5. Problemas con bluetooth"
-		echo "6. Problemas de sonido"
-		echo "7. Salir del programa"
-		echo -en "\nSeleccione una opción [1 - 7] "
-		read opcion
-		echo
-			case $opcion in
-			1) 	performance
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			2) 	touchpad
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			3) 	sudo true; ethernet
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			4) 	sudo true; wireless
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			5)	bluetooth
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			6)	sound
-				[[ "${#report[@]}" -eq 0 ]] && echo 'OK.'
-				key;;
-			7) 	exit 0
-				key;;
-			*) 	echo "'$opcion' es una opción invalida."
-				key;;
-			esac
-		unset report[@] # Reinicia variable
-	done
-}
-
-push () {
-	if [[ "$2" != "v" ]] || [[ "$2" == "v" && $verbose -eq 1 ]]; then
-		report=("${report[@]}" "$1")
-		echo "$1"
-	fi
-}
-
-function in_array() {
-  local x
-
-  entry=$1
-  shift 1
-  array=( "$@" )
-  [ -z "${array}" ] && return 1
-  [ -z "${entry}" ] && return 1
-  
-  for x in ${array[@]}; do
-    [ "${x}" == "${entry}" ] && return 0
-  done
-  
-  return 1
-}
-
-# Sistema de paquetes utilizado, distribución, etc
-describe () {	
-	if [[ ! -z $(which apt 2>/dev/null) ]]; then
-		pkgm='apt'
-		else 
-			if [[ ! -z $(which dnf 2>/dev/null) ]]; then
-				pkgm='dnf'	
-			else
-				if [[ ! -z $(which pacman 2>/dev/null) ]]; then
-					pkgm='pacman'
-				else
-					if [[ ! -z $(which emerge 2>/dev/null) ]]; then
-						pkgm='emerge'	
-					fi	
-				fi	
-			fi	
-	fi 	
-
-	distro=`((cat /etc/*-release 2>/dev/null)| egrep '^ID=' | cut -c4-)`
-}
-
-# Drivers en lista negra
-blacklist () {
-	blacklist=$(cat /etc/modprobe.d/*blacklist* 2>/dev/null | egrep '^blacklist ' | cut -d' ' -f2)
-}
-
 
 describe ; [[ -z $pkgm ]] && push "Package management desconocido"
 blacklist
